import json
import os

import boto3

# model ID/name to use in Bedrock; can be overridden via env var
MODEL = os.environ.get("BEDROCK_MODEL", "claude-sonnet-3.6")

# client is created once per container
_client = boto3.client("bedrock")


def text_to_sql(natural_query: str, schema: str) -> str:
    """Call Amazon Bedrock to translate a natural language query into an Athena SQL statement.

    :param natural_query: user-written request such as "show me the last hour of imps".
    :param schema: a text description of the Athena table structure (passed verbatim to the LLM).
    :returns: SQL string generated by the model.
    """
    prompt = (
        "You are an expert SQL writer for Amazon Athena. "
        "Given the schema below, emit only a valid SQL query that answers the request.\n\n"
        f"Schema:\n{schema}\n\n"
        f"Request: {natural_query}\n\nSQL:"
    )

    response = _client.invoke_model(
        modelId=MODEL,
        contentType="application/json",
        accept="application/json",
        body=json.dumps({"input": prompt}),
    )
    # response['body'] is a StreamingBody
    data = json.loads(response["body"].read())
    # different bedrock models return different keys, but most use 'outputText'
    return data.get("outputText", "").strip()
